!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "ON_EVENT$(TRIGGER$)",
"ARGS": [{"TRIGGER$": "STRING"}],
"RETURNS": "BOOLEAN",
"DESCRIPTION":
"
USE THIS FUNCTION IN YOUR MAIN LOOP RETURNS 
'TRUE' OR 'FALSE', IF THE (TRIGGER$) OCCURS
"
}
!!


FN.DEF ON_EVENT$(TRIGGER$)

   BUNDLE.GET      1, "EVENT HERIZON", EVENTS
   BUNDLE.GET EVENTS,      "TRIGGERS", TRIGGERS

   LIST.SIZE TRIGGERS, TOTAL_TRIGGERS
   
   IF TOTAL_TRIGGERS > 0
      LIST.SEARCH TRIGGERS, TRIGGER$, EXISTS
   END IF 

   IF EXISTS
      LIST.REMOVE TRIGGERS, EXISTS
      FN.RTN "TRUE"
   ELSE
      FN.RTN "FALSE"
   END IF 

FN.END