!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "CREATE_CLASS$(CLASS_NAME$)",
"ARGS": [{"CLASS_NAME": "UNIQUE CLASS NAME"}],
"RETURNS": "MEMORY ADDRESS",
"DESCRIPTION":
"
CREATE A NEW CLASS & LOAD REQUIRED PROPERTIES 
AUTOMATICALLY NAMING THE CLASS IN THE PROCESS 
"
}
!!


FN.DEF CREATE_CLASS$(CLASS_NAME$)

   ADDRESS$ = MM_CREATE$("C")
   CLASS    = MM_POINTER(ADDRESS$)
   
   BUNDLE.PUT    CLASS, "NAME",             "S"
   BUNDLE.PUT    CLASS, "INDEX",            "MA"
   BUNDLE.PUT    CLASS, "TYPE",             "S"
   BUNDLE.PUT    CLASS, "SUB TYPE",         "S"
   BUNDLE.PUT    CLASS, "TYPINGS",          "MA"
   BUNDLE.PUT    CLASS, "CLASS VARIABLES",  "MA"
   BUNDLE.PUT    CLASS, "OBJECT VARIABLES", "MA"

   EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "CREATE_CLASS()" + CHR$(34) + ", TYPE: " + CHR$(34) + "CLASS CREATION SUCCESS" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "SUCCESSFULLY CREATED A NEW CLASS NAMED '" + CLASS_NAME$ + "' AS '" + ADDRESS$ + "'" + CHR$(34) + "}}"
   
   LOG_EVENT$(EVENT$)
   
   INIT_CLASS(ADDRESS$, CLASS_NAME$)

   FN.RTN ADDRESS$
   
FN.END


!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "CREATE_CLASS(CLASS_NAME$)",
"ARGS": [{"CLASS_NAME": "UNIQUE CLASS NAME"}],
"RETURNS": "STRUCT ID",
"DESCRIPTION":
"
CREATE A NEW CLASS & LOAD REQUIRED PROPERTIES 
AUTOMATICALLY NAMING THE CLASS IN THE PROCESS 
"
}
!!


FN.DEF CREATE_CLASS(CLASS_NAME$)

   ADDRESS$ = CREATE_CLASS$(CLASS_NAME$)
   CLASS    = MM_POINTER(ADDRESS$)

   FN.RTN CLASS

FN.END
