!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "INIT_CLASS_NAME$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)",
"DESCRIPTION":
"
HELPER FUNCTION FOR INIT_CLASS(MM_ADDRESS$)
"
}
!!


FN.DEF INIT_CLASS_NAME$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)

   BUNDLE.PUT    INIT_CLASS, PROPERTY$, CLASS_NAME$
   BUNDLE.PUT    TYPINGS, PROPERTY$, "S"
   
   EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "INIT_CLASS_NAME$()" + CHR$(34) + ", TYPE: " + CHR$(34) + "CLASS PROPERTY 'NAME' INITIALIZATION SUCCESS" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "SUCCESSFULLY INITIALIZED CLASS PROPERTY 'NAME' AS '" + CLASS_NAME$ + "'" + CHR$(34) + "}}" 
   LOG_EVENT$(EVENT$)
   
FN.END


!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "INIT_CLASS_INDEX$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)",
"DESCRIPTION":
"
HELPER FUNCTION FOR INIT_CLASS(MM_ADDRESS$)
"
}
!!


FN.DEF INIT_CLASS_INDEX$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)

   MM_ADDRESS$ = MM_ADDRESS$(INIT_CLASS, "C")
   
   BUNDLE.PUT    INIT_CLASS, PROPERTY$, MM_ADDRESS$
   BUNDLE.PUT    TYPINGS, PROPERTY$, "MA"
   
   EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "INIT_CLASS_INDEX$()" + CHR$(34) + ", TYPE: " + CHR$(34) + "CLASS PROPERTY 'INDEX' INITIALIZATION SUCCESS" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "SUCCESSFULLY INITIALIZED CLASS PROPERTY 'INDEX' AS '" + MM_ADDRESS$ + "' FOR CLASS NAMED '" + CLASS_NAME$ + "'" + CHR$(34) + "}}" 
   LOG_EVENT$(EVENT$)

FN.END


!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "INIT_CLASS_TYPE$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)",
"DESCRIPTION":
"
HELPER FUNCTION FOR INIT_CLASS(MM_ADDRESS$)
"
}
!!


FN.DEF INIT_CLASS_TYPE$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)

   BUNDLE.PUT    INIT_CLASS, PROPERTY$, "CLASS"
   BUNDLE.PUT    TYPINGS, PROPERTY$, "S"
   
   EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "INIT_CLASS_TYPE$()" + CHR$(34) + ", TYPE: " + CHR$(34) + "CLASS PROPERTY 'TYPE' INITIALIZATION SUCCESS" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "SUCCESSFULLY INITIALIZED CLASS PROPERTY 'TYPE' AS 'CLASS' FOR CLASS NAMED '" + CLASS_NAME$ + "'" + CHR$(34) + "}}" 
   LOG_EVENT$(EVENT$)

FN.END


!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "INIT_CLASS_SUBTYPE$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)",
"DESCRIPTION":
"
HELPER FUNCTION FOR INIT_CLASS(MM_ADDRESS$)
"
}
!!


FN.DEF INIT_CLASS_SUBTYPE$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)

   BUNDLE.PUT    INIT_CLASS, PROPERTY$, "SUPER CLASS"
   BUNDLE.PUT    TYPINGS, PROPERTY$, "S"
   
   EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "INIT_CLASS_SUBTYPE$()" + CHR$(34) + ", TYPE: " + CHR$(34) + "CLASS PROPERTY 'SUB TYPE' INITIALIZATION SUCCESS" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "SUCCESSFULLY INITIALIZED CLASS PROPERTY 'SUB TYPE' AS 'SUPER CLASS' FOR CLASS NAMED '" + CLASS_NAME$ + "'" + CHR$(34) + "}}" 
   LOG_EVENT$(EVENT$)
   
FN.END


!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "INIT_CLASS_TYPINGS$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)",
"DESCRIPTION":
"
HELPER FUNCTION FOR INIT_CLASS(MM_ADDRESS$)
"
}
!!


FN.DEF INIT_CLASS_TYPINGS$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)

   MM_ADDRESS$ = MM_ADDRESS$(TYPINGS, "B")
   
   BUNDLE.PUT    INIT_CLASS, PROPERTY$, MM_ADDRESS$
   BUNDLE.PUT    TYPINGS, PROPERTY$, "MA"
   
   EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "INIT_CLASS_TYPINGS$()" + CHR$(34) + ", TYPE: " + CHR$(34) + "CLASS PROPERTY 'TYPINGS' INITIALIZATION SUCCESS" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "SUCCESSFULLY INITIALIZED CLASS PROPERTY 'TYPINGS' AS '" + MM_ADDRESS$ + "' FOR 'PROPERTIES' OF CLASS NAMED '" + CLASS_NAME$ + "'" + CHR$(34) + "}}" 
   LOG_EVENT$(EVENT$)

FN.END


!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "INIT_CLASS_CLASSVARIABLES$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)",
"DESCRIPTION":
"
HELPER FUNCTION FOR INIT_CLASS(MM_ADDRESS$)
"
}
!!


FN.DEF INIT_CLASS_CLASSVARIABLES$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)

   CLASS_VARIABLES$ = MM_CREATE$("B")
   CLASS_VARIABLES  = MM_POINTER(CLASS_VARIABLES$)
   
   BUNDLE.PUT    CLASS_VARIABLES, "CLASS NAME", CLASS_NAME$
   BUNDLE.PUT    INIT_CLASS, PROPERTY$, CLASS_VARIABLES$
   BUNDLE.PUT    TYPINGS, PROPERTY$, "MA"

   EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "INIT_CLASS_SUBTYPE$()" + CHR$(34) + ", TYPE: " + CHR$(34) + "CLASS PROPERTY 'CLASS VARIABLES' INITIALIZATION SUCCESS" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "SUCCESSFULLY INITIALIZED CLASS PROPERTY 'CLASS VARIABLES' AS '" + CLASS_VARIABLES$ + "' FOR CLASS NAMED '" + CLASS_NAME$ + "'" + CHR$(34) + "}}" 
   LOG_EVENT$(EVENT$)

FN.END


!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "INIT_CLASS_OBJECTVARIABLES$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)",
"DESCRIPTION":
"
HELPER FUNCTION FOR INIT_CLASS(MM_ADDRESS$)
"
}
!!


FN.DEF INIT_CLASS_OBJECTVARIABLES$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)

   BUNDLE.PUT    INIT_CLASS, PROPERTY$, DEFAULT_VALUE
   BUNDLE.PUT    TYPINGS, PROPERTY$, "B" 

   EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "INIT_CLASS_OBJECTVARIABLES$()" + CHR$(34) + ", TYPE: " + CHR$(34) + "CLASS PROPERTY 'OBJECT VARIABLES' INITIALIZATION SUCCESS" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "SUCCESSFULLY INITIALIZED CLASS PROPERTY 'OBJECT VARIABLES' FOR CLASS NAMED '" + CLASS_NAME$ + "'" + CHR$(34) + "}}" 
   LOG_EVENT$(EVENT$)

FN.END


!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "INIT_CLASS_STRING$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)",
"DESCRIPTION":
"
HELPER FUNCTION FOR INIT_CLASS(MM_ADDRESS$)
"
}
!!


FN.DEF INIT_CLASS_STRING$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)

   BUNDLE.PUT    INIT_CLASS, PROPERTY$, "DEFAULT VALUE"
   BUNDLE.PUT    TYPINGS, PROPERTY$, "S"
   
   EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "INIT_CLASS_STRING$()" + CHR$(34) + ", TYPE: " + CHR$(34) + "CLASS PROPERTY '" + PROPERTY$ + "' INITIALIZATION SUCCESS" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "SUCCESSFULLY INITIALIZED CLASS PROPERTY '" + PROPERTY$ + "' FOR CLASS NAMED '" + CLASS_NAME$ + "'" + CHR$(34) + "}}" 
   LOG_EVENT$(EVENT$)

FN.END


!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "INIT_CLASS_NUMERIC$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)",
"DESCRIPTION":
"
HELPER FUNCTION FOR INIT_CLASS(MM_ADDRESS$)
"
}
!!


FN.DEF INIT_CLASS_NUMERIC$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)

   BUNDLE.PUT    INIT_CLASS, PROPERTY$, 0
   BUNDLE.PUT    TYPINGS, PROPERTY$, "N"
   
   EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "INIT_CLASS_NUMERIC$()" + CHR$(34) + ", TYPE: " + CHR$(34) + "CLASS PROPERTY '" + PROPERTY$ + "' INITIALIZATION SUCCESS" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "SUCCESSFULLY INITIALIZED CLASS PROPERTY '" + PROPERTY$ + "' FOR CLASS NAMED '" + CLASS_NAME$ + "'" + CHR$(34) + "}}" 
   LOG_EVENT$(EVENT$)

FN.END


!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "INIT_CLASS_STRINGL$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)",
"DESCRIPTION":
"
HELPER FUNCTION FOR INIT_CLASS(MM_ADDRESS$)
"
}
!!


FN.DEF INIT_CLASS_STRINGL$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)

   BUNDLE.PUT    INIT_CLASS, PROPERTY$, 0
   BUNDLE.PUT    TYPINGS, PROPERTY$, "SL"
   
   EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "INIT_CLASS_STRINGL$()" + CHR$(34) + ", TYPE: " + CHR$(34) + "CLASS PROPERTY '" + PROPERTY$ + "' INITIALIZATION SUCCESS" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "SUCCESSFULLY INITIALIZED CLASS PROPERTY '" + PROPERTY$ + "' FOR CLASS NAMED '" + CLASS_NAME$ + "'" + CHR$(34) + "}}" 
   LOG_EVENT$(EVENT$)

FN.END


!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "INIT_CLASS_NUMERICL$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)",
"DESCRIPTION":
"
HELPER FUNCTION FOR INIT_CLASS(MM_ADDRESS$)
"
}
!!


FN.DEF INIT_CLASS_NUMERICL$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)

   BUNDLE.PUT    INIT_CLASS, PROPERTY$, 0
   BUNDLE.PUT    TYPINGS, PROPERTY$, "NL"
   
   EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "INIT_CLASS_NUMERICL$()" + CHR$(34) + ", TYPE: " + CHR$(34) + "CLASS PROPERTY '" + PROPERTY$ + "' INITIALIZATION SUCCESS" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "SUCCESSFULLY INITIALIZED CLASS PROPERTY '" + PROPERTY$ + "' FOR CLASS NAMED '" + CLASS_NAME$ + "'" + CHR$(34) + "}}" 
   LOG_EVENT$(EVENT$)

FN.END


!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "INIT_CLASS_B$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)",
"DESCRIPTION":
"
HELPER FUNCTION FOR INIT_CLASS(MM_ADDRESS$)
"
}
!!


FN.DEF INIT_CLASS_B$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)

   BUNDLE.PUT    INIT_CLASS, PROPERTY$, SPECIAL_TYPE
   BUNDLE.PUT    TYPINGS, PROPERTY$, "B"
   
   EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "INIT_CLASS_NUMERICL$()" + CHR$(34) + ", TYPE: " + CHR$(34) + "CLASS PROPERTY '" + PROPERTY$ + "' INITIALIZATION SUCCESS" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "SUCCESSFULLY INITIALIZED CLASS PROPERTY '" + PROPERTY$ + "' FOR CLASS NAMED '" + CLASS_NAME$ + "'" + CHR$(34) + "}}" 
   LOG_EVENT$(EVENT$)

FN.END


!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "INIT_CLASS_P$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)",
"DESCRIPTION":
"
HELPER FUNCTION FOR INIT_CLASS(MM_ADDRESS$)
"
}
!!


FN.DEF INIT_CLASS_P$(INIT_CLASS, PROPERTY$, TYPINGS, CLASS_NAME$)

   BUNDLE.PUT    INIT_CLASS, PROPERTY$, SPECIAL_TYPE
   BUNDLE.PUT    TYPINGS, PROPERTY$, "P"
   
   EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "INIT_CLASS_NUMERICL$()" + CHR$(34) + ", TYPE: " + CHR$(34) + "CLASS PROPERTY '" + PROPERTY$ + "' INITIALIZATION SUCCESS" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "SUCCESSFULLY INITIALIZED CLASS PROPERTY '" + PROPERTY$ + "' FOR CLASS NAMED '" + CLASS_NAME$ + "'" + CHR$(34) + "}}" 
   LOG_EVENT$(EVENT$)

FN.END