!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "ADD_PROPERTY$(CLASS_ADDRESS$, PROPERTY$, TYPE$)",
"ARGS": ["CLASS_ADDRESS$": ""],
"RETURNS": "MEMORY ADDRESS",
"DESCRIPTION":
"
ADD PROPERTY (PROPERTY$) AS STRING TO AN rfOOP 
CLASS: CURRENTLY SUPPORTS (TYPE$) 'S' AND 'SL'
"
}
!!


FN.DEF ADD_PROPERTY$(CLASS_ADDRESS$, PROPERTY$, TYPE$)

   IF MM_VALIDATE$(CLASS_ADDRESS$) = "FALSE"
      EVENT$ = "{EVENT:{FUNCTION: " + CHR$(34) + "ADD_PROPERTY$()" + CHR$(34) + ", TYPE: " + CHR$(34) + "PROPERTY ADDITION FAILURE" + CHR$(34) + ", MESSAGE: " + CHR$(34) + "FAILED TO ADD '" + PROPERTY$ + "' AS A PROPERTY OF '" + CLASS_ADDRESS$ + "'" + CHR$(34) + "}}"
   
      LOG_EVENT$(EVENT$)
      FN.RTN EVENT$      
   END IF 

   IF TYPE$ = "S"
      BUNDLE.PUT CLASS, PROPERTY$, "DEFAULT VALUE"
      LOG_EVENT$("PASS", "PROPERTY ADDITION SUCCESS: NEW PROPERTY '" + PROPERTY$ + "' OF 'STRING' TYPE HAS BEEN ADDED TO CLASS '" + GET_NAME$(CLASS) + "'") 
   ELSEIF TYPE$ = "SL"
      BUNDLE.PUT CLASS, PROPERTY$, DEFAULT_VALUE
      LOG_EVENT$("PASS", "PROPERTY ADDITION SUCCESS: NEW PROPERTY '" + PROPERTY$ + "' OF 'STRING LIST' TYPE HAS BEEN ADDED TO CLASS '" + GET_NAME$(CLASS) + "'")
   ELSE
      LOG_EVENT$("FAIL", "PROPERTY ADDITION FAILURE: ERROR ADDING PROPERTY: '" + PROPERTY$ + "' DUE TO TYPE MISMATCH, PLEASE SPECIFY 'S' OR 'SL' FOR TYPE AS STRING OR USE ADD_PROPERTY() INSTEAD FOR NUMERIC TYPE")
   END IF

   BUNDLE.GET CLASS, "TYPINGS", TYPINGS
   BUNDLE.PUT TYPINGS, PROPERTY$, TYPE$
   LOAD_THIS(CLASS)

FN.END


!>-------------------------------------------------------------------------------
!!
VER: 0.1
LIB: rfOOP_CLASSES
FUNCTION: ADD_PROPERTY(CLASS, PROPERTY$, TYPE$)
ADD A PROPERTY (PROPERTY$) AS NUMERIC TYPE TO AN rfOOP 
CLASS: CURRENTLY SUPPORTS (TYPE$) "N" "NL" "B" AND "P"
!!


FN.DEF ADD_PROPERTY(CLASS, PROPERTY$, TYPE$)

   IF MM_VALIDATE$(CLASS) = "PASS"
      IF TYPE$ = "N"
         BUNDLE.PUT CLASS, PROPERTY$, DEFAULT_VALUE
         LOG_EVENT$("PASS", "PROPERTY ADDITION SUCCESS: NEW PROPERTY '" + PROPERTY$ + "' OF '" + TYPE$ + "' TYPE HAS BEEN ADDED TO CLASS '" + GET_NAME$(CLASS) + "'")
      ELSEIF TYPE$ = "NL"         
         BUNDLE.PUT CLASS, PROPERTY$, DEFAULT_VALUE
         LOG_EVENT$("PASS", "PROPERTY ADDITION SUCCESS: NEW PROPERTY '" + PROPERTY$ + "' OF '" + TYPE$ + "' TYPE HAS BEEN ADDED TO CLASS '" + GET_NAME$(CLASS) + "'")
      ELSEIF TYPE$ = "B"
         BUNDLE.PUT CLASS, PROPERTY$, DEFAULT_VALUE
         LOG_EVENT$("PASS", "PROPERTY ADDITION SUCCESS: NEW PROPERTY '" + PROPERTY$ + "' OF '" + TYPE$ + "' TYPE HAS BEEN ADDED TO CLASS '" + GET_NAME$(CLASS) + "'")
      ELSEIF TYPE$ = "P"
         BUNDLE.PUT CLASS, PROPERTY$, DEFAULT_VALUE
         LOG_EVENT$("PASS", "PROPERTY ADDITION SUCCESS: NEW PROPERTY '" + PROPERTY$ + "' OF '" + TYPE$ + "' TYPE HAS BEEN ADDED TO CLASS '" + GET_NAME$(CLASS) + "'")
      ELSE
         LOG_EVENT$("FAIL", "PROPERTY ADDITION FAILURE: ERROR ADDING PROPERTY: '" + PROPERTY$ + "' DUE TO TYPE MISMATCH, PLEASE SPECIFY 'N' 'NL' 'B' OR 'P' FOR TYPE AS NUMERIC OR USE ADD_PROPERTY$() INSTEAD FOR STRING TYPE")
      END IF
   ELSE
      LOG_EVENT$("PASS", "PROPERTY ADDITION FAILURE: THE PROPERTY NAMED '" + PROPERTY$ + "'ALREADY EXISTS")
   END IF 
   
   BUNDLE.GET CLASS, "TYPINGS", TYPINGS
   BUNDLE.PUT TYPINGS, PROPERTY$, TYPE$
   LOAD_THIS(CLASS)

FN.END

