!>-------------------------------------------------------------------------------
!!
VER: 0.1
LIB: PROPERTIES
FUNCTION: ALLOW_PRIVATE(CLASS)
THIS FUNCTION WILL ALLOW (CLASS) TO HAVE USER DEFINED 
PRIVATE PROPERTIES OUTSIDE OF THE SYSTEM DEFINED ONES
!!


FN.DEF ALLOW_PRIVATE(CLASS)

   IF VARIABLE_EXISTS$(CLASS, "PRIVATE_PROPERTIES") = "FALSE"
      LIST.CREATE S, PRIVATE_PROPERTIES
      ADD_VARIABLE$(CLASS, "PRIVATE_PROPERTIES", "N")
   END IF 
   SET_VARIABLE(CLASS, "PRIVATE_PROPERTIES", PRIVATE_PROPERTIES)
   
FN.END

