!>-------------------------------------------------------------------------------
!!
VER: 0.1
LIB: PROPERTIES
FUNCTION: GET_PROPERTIES(SELF)
GET A LIST OF PROPERTIES
ASSOCIATED WITH (SELF)
!!


FN.DEF GET_PROPERTIES(SELF)

   BUNDLE.KEYS SELF, PROPERTIES
   
   LIST.SIZE PROPERTIES, TOTAL_PROPERTIES

   IF TOTAL_PROPERTIES > 1
      LOG_EVENT$("PASS", "SUCCESSFULLY RETRIEVED PROPERTIES OF '" + GET_NAME$(SELF) + "'")
      FN.RTN PROPERTIES
   ELSE
      LOG_EVENT$("FAIL", "OBJECT OR CLASS DOES NOT EXIST, NO PROPERTIES TO GET")
   END IF

PRINT "DONE GET PROPERTIES"

FN.END
