!>-------------------------------------------------------------------------------
!!
VER: 0.1
LIB: PROPERTIES
FUNCTION: MAKE_PRIVATE$(CLASS, PROPERTY$)
USE AFTER ALLOWING PRIVATE PROPERTIES
TO MAKE (PROPERTY$) OF (CLASS) PRIVATE
!!


FN.DEF MAKE_PRIVATE$(CLASS, PROPERTY$)

   PROPERTIES = GET_PROPERTIES(CLASS)
   LIST.SEARCH PROPERTIES, PROPERTY$, PROPERTY_EXISTS

   IF PROPERTY_EXISTS
   
      PRIVATE_PROPERTIES = GET_VARIABLE(CLASS, "PRIVATE_PROPERTIES")
      LIST.SEARCH PRIVATE_PROPERTIES, PROPERTY$, EXISTS
      PRINT "EXISTS" + STR$(EXISTS)
      
      IF !EXISTS 
   
         LIST.ADD PRIVATE_PROPERTIES, PROPERTY$
      
      END IF 
      
      LIST.SIZE PRIVATE_PROPERTIES, SIZE
      PRINT "SIZE IS " + STR$(SIZE)
      SET_VARIABLE(CLASS, "PRIVATE_PROPERTIES", PRIVATE_PROPERTIES)
      
   ELSE
   
   END IF 

FN.END
