!>-------------------------------------------------------------------------------
!!
VER: 0.1
LIB: PROPERTIES
FUNCTION: PUBLIC_PROPERTIES(CLASS)
THIS FUNCTION RETURNS A LIST 
OF THE PROPERTIES OF (CLASS)
!!


FN.DEF PUBLIC_PROPERTIES(CLASS)

   PROPERTIES = GET_PROPERTIES(CLASS)

   LIST.SEARCH PROPERTIES, "NAME", NAME
   LIST.REMOVE PROPERTIES, NAME
   LIST.SEARCH PROPERTIES, "TYPE", TYPE
   LIST.REMOVE PROPERTIES, TYPE
   LIST.SEARCH PROPERTIES, "SUB TYPE", SUB_TYPE
   LIST.REMOVE PROPERTIES, SUB_TYPE
   LIST.SEARCH PROPERTIES, "TYPINGS", TYPINGS
   LIST.REMOVE PROPERTIES, TYPINGS
   LIST.SEARCH PROPERTIES, "INDEX", INDEX
   LIST.REMOVE PROPERTIES, INDEX
   LIST.SEARCH PROPERTIES, "CLASS VARIABLES", CLASS_VARIABLES
   LIST.REMOVE PROPERTIES, CLASS_VARIABLES
   LIST.SEARCH PROPERTIES, "OBJECT VARIABLES", OBJECT_VARIABLES
   LIST.REMOVE PROPERTIES, OBJECT_VARIABLES
   
   IF VARIABLE_EXISTS$(CLASS, "PRIVATE_PROPERTIES") <> "FALSE"
   
      USER_PROPERTIES = GET_VARIABLE(CLASS, "PRIVATE_PROPERTIES")
      LIST.SIZE USER_PROPERTIES, TOTAL_PROPERTIES
      
      FOR PROPERTY = 1 TO TOTAL_PROPERTIES
      
         LIST.GET USER_PROPERTIES, PROPERTY, PROPERTY$
         LIST.SEARCH PROPERTIES, PROPERTY$, INDEX
         LIST.REMOVE PROPERTIES, INDEX 
      
      NEXT PROPERTY
      
   END IF

   FN.RTN PROPERTIES

FN.END
