!>-------------------------------------------------------------------------------
!!
VER: 0.1
LIB: PROPERTIES
FUNCTION: PROPERTY_TYPE$(SELF, PROPERTY$)
GET THE TYPE OF PROPERTY DEFINED AS (PROPERTY$)
FROM AN rfOOP OBJECT OR A rfOOP CLASS (SELF)
!!


FN.DEF PROPERTY_TYPE$(SELF, PROPERTY$)

   BUNDLE.KEYS SELF, KEYS

   LIST.SEARCH KEYS, PROPERTY$, EXISTS

   IF EXISTS <> 0     
      BUNDLE.TYPE SELF, PROPERTY$, TYPE$               
      IF TYPE$ = "S"
         LOG_EVENT$("PASS", "SUCCESSFULLY RETRIEVED TYPE '" + TYPE$ + "' OF PROPERTY DEFINED AS '" + PROPERTY$ + "' FROM '" + GET_NAME$(SELF) + "'")
      ELSE IF TYPE$ = "N"
         LOG_EVENT$("PASS", "SUCCESSFULLY RETRIEVED TYPE '" + TYPE$ + "' OF PROPERTY DEFINED AS '" + PROPERTY$ + "' FROM '" + GET_NAME$(SELF) + "'")
      END IF
   ELSE
      LOG_EVENT$("FAIL", "THE PROPERTY DEFINED AS '" + PROPERTY$ + "' FROM '" + GET_NAME$(SELF) + "' DOES NOT EXIST")
   END IF

FN.RTN TYPE$

FN.END
