!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "THIS_OBJECTVARIABLES()",
"RETURNS": "STRUCT ID",
"DESCRIPTION":
"
PEEK AT THE rfoMM STACK MANAGEMENT SYSTEM AND RETURN
OBJECT VARIABLE BUNDLE OF THE CURRENT OBJECT / CLASS
"
}
!!


FN.DEF THIS_OBJECTVARIABLES()

   BUNDLE.GET 1, "rfoMM", rfoMM
   BUNDLE.GET rfoMM, "rfOOP_STACK", THIS
   
   STACK.ISEMPTY THIS, EXISTS
   
   IF !EXISTS
      STACK.PEEK THIS, CURRENT   
      BUNDLE.GET CURRENT, "OBJECT VARIABLES", OBJECT_VARIABLES
      FN.RTN OBJECT_VARIABLES
   ELSE
      EVENT$ = "{" + CHR$(34) + "EVENT" + CHR$(34) + ":{" + CHR$(34) + "FUNCTION" + CHR$(34) + ": " + CHR$(34) + "THIS_OBJECTVARIABLES$()" + CHR$(34) + ", " + CHR$(34) + "TYPE" + CHR$(34) + ": " + CHR$(34) + "FAILURE GETTING THIS OBJECT VARIABLES" + CHR$(34) + ", " + CHR$(34) + "MESSAGE" + CHR$(34) + ": " + CHR$(34) + "NOTHING LOADED IN THIS STACK}}"
      LOG_EVENT$(EVENT$)
   END IF 

FN.END