!>-------------------------------------------------------------------------------
!!
{
"FUNCTION": "THIS_CLASSVARIABLES()",
"RETURNS": "STRUCT ID",
"DESCRIPTION":
"
PEEK AT THE rfoMM STACK MANAGEMENT SYSTEM AND RETURN
THE CLASS VARIABLE BUNDLE OF CURRENT OBJECT OR CLASS
"
}
!!


FN.DEF THIS_CLASSVARIABLES()

   BUNDLE.GET 1, "rfoMM", rfoMM
   BUNDLE.GET rfoMM, "rfOOP_STACK", THIS
   
   STACK.ISEMPTY THIS, EXISTS
   
   IF !EXISTS
      STACK.PEEK THIS, CURRENT   
      BUNDLE.GET CURRENT, "CLASS VARIABLES", CLASS_VARIABLES
      FN.RTN CLASS_VARIABLES
   ELSE
      EVENT$ = "{" + CHR$(34) + "EVENT" + CHR$(34) + ":{" + CHR$(34) + "FUNCTION" + CHR$(34) + ": " + CHR$(34) + "THIS_CLASSVARIABLES$()" + CHR$(34) + ", " + CHR$(34) + "TYPE" + CHR$(34) + ": " + CHR$(34) + "FAILURE GETTING THIS CLASS VARIABLES" + CHR$(34) + ", " + CHR$(34) + "MESSAGE" + CHR$(34) + ": " + CHR$(34) + "NOTHING LOADED IN THIS STACK}}"
      LOG_EVENT$(EVENT$)
   END IF 

FN.END